### ISSUE TITLE
需要Tab页的图标排列优化。

### ISSUE THREAD

**Issue by junboy8818** [luolingchun/PyQRibbon#4]
能否修改class QTab(QBaseWidget)类，在其中添加一个类似addGroup（）的方法， 在Tab页中添加一个group组时，去掉组最下面的的组名及组名所占的位置。
比如：class QGroup(QBaseWidget):
    def __init__(self, name, widget, corner=False, cornerCallback=None, parent=None):
        """
        组控件
        :param name: 名称
        :param widget: 控件
        :param corner: 右下角按钮是否实现显示
        :param cornerCallback: 右下角按钮点击回调函数
        :param parent: 父级
        """
不想要:param corner参数和这个参数所占的控件位置。

**Comment by luolingchun** [comment]
@junboy8818 你的意思是可以控制不显示组下面的名称和右下角的corner按钮？

**Comment by junboy8818** [comment]
对的，正是这个意思

**Comment by junboy8818** [comment]
@luolingchun   对的，就是可以控制不显示组下面的名称和右下角的corner按钮，并且它占用的位置也不要。现在虽然可以控制它不显示，但它会空出一个位置在那里不好看。

**Comment by junboy8818** [comment]
因为我需要的一个工具栏，图标较少，每tab页基本上是从左到右依次排列， addGroup中能控制加与不加竖线？我是初学新手，不太会弄，谢谢您的帮助！

**Comment by luolingchun** [comment]
@junboy8818 我新建了一个[tab分支](https://github.com/luolingchun/PyQRibbon/tree/tab)，有时间测试一下，没有问题了我再合并代码，发布版本

**Comment by junboy8818** [comment]
经测试，分组名称、角落按钮、竖线支持可选，功能正常
